# Generated by Django 3.1.4 on 2021-01-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210120_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='row',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='hall',
            name='columns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hall',
            name='rows',
            field=models.IntegerField(default=0),
        ),
    ]
