# Generated by Django 3.1.4 on 2021-01-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210120_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hall', to='movies.hall'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie', to='movies.movie'),
        ),
    ]
