# Generated by Django 3.1.4 on 2021-01-20 16:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210120_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='screening',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.screening'),
        ),
    ]
