# Generated by Django 3.1.4 on 2021-01-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20210121_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=100),
        ),
    ]
