# Generated by Django 3.1.4 on 2021-01-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20210121_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='relevant',
            field=models.BooleanField(default=False),
        ),
    ]
