# Generated by Django 3.1.5 on 2021-01-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_ticket_istemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
