# Generated by Django 3.1.4 on 2021-01-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ageLimit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
