# Generated by Django 3.1.5 on 2021-01-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20210123_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='countRatings',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='sumRatings',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
