# Generated by Django 3.1.5 on 2021-01-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20210123_2242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='screening',
            unique_together={('hall', 'screenDate')},
        ),
    ]
